name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Static check (imports)
        run: |
          python -c "import fastapi, sqlalchemy, alembic"
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
